name: department_bloc
description: Department BLoC for medical records app
version: 1.0.0
publish_to: 'none'
resolution: workspace

environment:
  sdk: '>=3.9.2 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_database: any
  bloc: ^9.0.0
  equatable: ^2.0.5
  drift: ^2.28.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  build_runner: ^2.5.4

flutter: