name: hospital_form_bloc
description: Hospital form BLoC for medical records app
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # No assets or fonts needed for this package