name: visit_form_widget
description: A reusable visit form widget for the medical records app.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: '^3.9.2'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_form_bloc:
    path: ../../third_party/flutter_form_bloc
  app_locale:
    path: ../../app_lib/locale
  app_database:
    path: ../../app_lib/database
  visit_form_bloc:
    path: ../../app_bloc/visit_form_bloc
  hospital_bloc:
    path: ../../app_bloc/hospital
  hospital_form_bloc:
    path: ../../app_bloc/hospital_form_bloc
  hospital_form:
    path: ../../app_widget/hospital_form

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: false