name: app_provider
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17

  theme_bloc: any
  app_database: any
  treatment_bloc: any
  visit_bloc: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
